// Generates contracts/generated/types.ts from contracts/generated/schema.json.
// Source of truth is the Pydantic models; never edit the output by hand.
import { compileFromFile } from "json-schema-to-typescript";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const schema = fileURLToPath(new URL("../../contracts/generated/schema.json", import.meta.url));
const out = fileURLToPath(new URL("../../contracts/generated/types.ts", import.meta.url));

const banner =
  "/* GENERATED by `make contracts` from contracts/generated/schema.json.\n" +
  " * Source of truth: Pydantic models in contracts/. DO NOT EDIT BY HAND. */";

const ts = await compileFromFile(schema, {
  bannerComment: banner,
  additionalProperties: false,
  unreachableDefinitions: true,
  format: false,
});
writeFileSync(out, ts.replace(/\r\n/g, "\n"), "utf8");
console.log(`wrote ${out}`);
