"""Plain-language glossary (decision B-36): the single source of user-facing wording.

Every enum value a reader can see (coverage state, final state, verdict, challenge outcome, conflict
kind and status, stop reason, failure, source status, certainty) maps to a plain label, a one-line
meaning and a next step. The frontend reads `contracts/generated/glossary.ts` (generated by
`contracts/schema_export.py`) and the Markdown report renderer reads this module, so the two can
never drift. Stored values and enum names do not change; only what people read does.

The headline labels for `final_state` and `coverage_state` are fixed by the project owner; a test
pins them. A missing entry for any enum value fails `tests/unit/test_glossary.py`.
"""

# ruff: noqa: E501  (user-facing prose stays on one line per string)
from __future__ import annotations

from pydantic import BaseModel

from contracts.events import EventType
from contracts.models import (
    CertaintyLabel,
    ChallengeOutcome,
    ConflictKind,
    ConflictStatus,
    CoverageState,
    FailureType,
    FinalState,
    Phase,
    SourceStatus,
    TerminationReason,
    Verdict,
)


class GlossaryEntry(BaseModel):
    label: str  # short plain-English name shown on chips and headings
    meaning: str  # one sentence: what this result means
    next_step: str  # one sentence: what a reader can do about it ("" when nothing is needed)


def _e(label: str, meaning: str, next_step: str = "") -> GlossaryEntry:
    return GlossaryEntry(label=label, meaning=meaning, next_step=next_step)


# Non-enum key for a challenge that has no outcome yet.
CHALLENGE_PENDING = "pending"

GLOSSARY: dict[str, dict[str, GlossaryEntry]] = {
    # Traffic light per evidence slot and dimension (RED / AMBER / GREEN).
    "coverage_state": {
        CoverageState.GREEN.value: _e(
            "Well supported",
            "Enough independent sources agree on this point.",
        ),
        CoverageState.AMBER.value: _e(
            "Partly supported",
            "There is some evidence, but it is thin, from too few independent sources, or disputed.",
            "Treat this point with care, or run a follow-up to find another independent source.",
        ),
        CoverageState.RED.value: _e(
            "Not enough evidence",
            "No usable evidence was found for this point, or the evidence goes against it.",
            "Do not rely on this point until more evidence is found.",
        ),
    },
    # The headline answer to "is this research done?".
    "final_state": {
        FinalState.SUFFICIENT.value: _e(
            "Answer is solid",
            "The evidence gathered is enough to answer the question.",
        ),
        FinalState.SUFFICIENT_WITH_CAVEATS.value: _e(
            "Answer is solid, with caveats",
            "The evidence is enough to answer, with the caveats listed alongside.",
            "Read the caveats before acting on the answer.",
        ),
        FinalState.INSUFFICIENT.value: _e(
            "Not enough to answer yet",
            "The evidence is not enough to answer with confidence. This is a valid outcome, not an error.",
            "See what is missing, then run a follow-up with a larger budget or a narrower question.",
        ),
    },
    # A judge's verdict on one claim against its source passage.
    "verdict": {
        Verdict.SUPPORTS.value: _e("Backs the claim", "The source passage states this claim."),
        Verdict.PARTIAL.value: _e(
            "Partly backs the claim",
            "The source passage states part of this claim, or with limits.",
        ),
        Verdict.CONTRADICTS.value: _e(
            "Goes against the claim",
            "The source passage says something that conflicts with this claim.",
        ),
        Verdict.IRRELEVANT.value: _e(
            "Not relevant", "The source passage does not address this claim."
        ),
    },
    # What happened when the agent tried to disprove its own conclusion.
    "challenge_outcome": {
        ChallengeOutcome.STRENGTHENED.value: _e(
            "Held up under challenge",
            "The agent looked for evidence against this point and found none that changes it.",
        ),
        ChallengeOutcome.WEAKENED.value: _e(
            "Weakened by challenge",
            "The agent found evidence that makes this point less certain.",
            "Check the conflicting source before relying on this point.",
        ),
        ChallengeOutcome.UNRESOLVED.value: _e(
            "Challenge inconclusive",
            "The agent could not settle this either way.",
            "Treat this point as open.",
        ),
        CHALLENGE_PENDING: _e(
            "Not challenged yet", "No challenge result has been recorded for this attack."
        ),
    },
    "conflict_kind": {
        ConflictKind.UNIT_ERROR.value: _e(
            "Different units",
            "The sources use different units, such as per day and per month, so the numbers only look different.",
        ),
        ConflictKind.SCOPE_DIFFERENCE.value: _e(
            "Different scope",
            "The sources describe different places, groups or products, so they do not truly disagree.",
        ),
        ConflictKind.TEMPORAL.value: _e(
            "Different time period",
            "The sources describe different dates or periods, so the numbers differ.",
        ),
        ConflictKind.DEFINITION.value: _e(
            "Different definition",
            "The sources define the measured term differently.",
        ),
        ConflictKind.GENUINE.value: _e(
            "Real disagreement",
            "The sources truly disagree and the difference is not explained by units, scope, time or definition.",
            "Decide which source to trust, or treat the figure as a range.",
        ),
    },
    "conflict_status": {
        ConflictStatus.OPEN.value: _e(
            "Not yet explained",
            "Two sources disagree and the reason has not been established.",
            "Open the two claims and compare their sources.",
        ),
        ConflictStatus.EXPLAINED.value: _e(
            "Explained", "The difference between the two sources has been explained."
        ),
    },
    # Why the research loop stopped.
    "termination_reason": {
        TerminationReason.CRITERIA_MET.value: _e(
            "Enough evidence found",
            "Every critical point is well supported and the agent finished challenging its own conclusion.",
        ),
        TerminationReason.NO_MARGINAL_GAIN.value: _e(
            "More searching was not helping",
            "Another round was not adding new evidence, so the agent stopped.",
        ),
        TerminationReason.MAX_ROUNDS.value: _e(
            "Follow-up limit reached",
            "The agent used every follow-up round it is allowed.",
            "Raise the round limit or narrow the question to go further.",
        ),
        TerminationReason.BUDGET.value: _e(
            "Budget used up",
            "A budget limit was reached, so the run wrapped up with the evidence in hand.",
            "Run again with a larger budget to go further.",
        ),
        TerminationReason.TIMEOUT.value: _e(
            "Time limit reached",
            "The time limit was reached, so the run wrapped up with the evidence in hand.",
            "Run again with a longer time limit to go further.",
        ),
        TerminationReason.USER_STOPPED.value: _e(
            "Stopped by you", "The run was stopped by the user."
        ),
        TerminationReason.BLOCKED.value: _e(
            "Stopped by a failure",
            "A failure blocked the run, so it wrapped up with the evidence in hand.",
            "Check the failure shown in the activity log, then run again.",
        ),
    },
    # Typed failures (SSOT section 18): always shown, never hidden.
    "failure": {
        FailureType.RATE_LIMITED.value: _e(
            "Provider was busy", "A search or AI provider asked the agent to slow down."
        ),
        FailureType.SOURCE_UNAVAILABLE.value: _e(
            "Page could not be opened", "The source could not be fetched."
        ),
        FailureType.SOURCE_EMPTY.value: _e(
            "Page had no usable text", "The source was fetched but had no readable content."
        ),
        FailureType.STEP_FAILED.value: _e(
            "A step failed", "One step could not finish after retries."
        ),
        FailureType.CLAIM_REJECTED.value: _e(
            "Claim rejected by checks",
            "The claim was dropped because its quote could not be found in the source.",
        ),
        FailureType.BLOCKED.value: _e("Run blocked", "A failure stopped the run from continuing."),
    },
    "source_status": {
        SourceStatus.FOUND.value: _e("Found", "The source was found by search but not read yet."),
        SourceStatus.FETCHED.value: _e("Read", "The source page was opened and read."),
        SourceStatus.SOURCE_UNAVAILABLE.value: _e(
            "Page could not be opened", "The source could not be fetched."
        ),
        SourceStatus.SOURCE_EMPTY.value: _e(
            "Page had no usable text", "The source was fetched but had no readable content."
        ),
    },
    # Per-finding label in the report.
    "certainty": {
        CertaintyLabel.SUPPORTED.value: _e(
            "Backed by independent sources",
            "Independent sources back this finding.",
        ),
        CertaintyLabel.CONTESTED.value: _e(
            "Sources disagree",
            "Sources disagree about this finding and the disagreement is not settled.",
            "Do not rely on the figure without checking the conflict.",
        ),
        CertaintyLabel.SINGLE_ORIGIN.value: _e(
            "Rests on one source",
            "Only one independent origin backs this finding.",
            "Find a second independent source before relying on it.",
        ),
        CertaintyLabel.ASSUMED.value: _e(
            "System inference",
            "This was inferred by the system, not stated in a source.",
        ),
    },
    # The ten lifecycle steps the progress view shows (Phase enum).
    "phase": {
        Phase.PLAN.value: _e(
            "Planning", "Working out which points the question needs and what to search for."
        ),
        Phase.DISCOVER.value: _e(
            "Finding sources", "Searching the web for pages that may answer each point."
        ),
        Phase.ACQUIRE.value: _e(
            "Reading sources", "Downloading and storing the pages that were found."
        ),
        Phase.EXTRACT.value: _e(
            "Pulling out facts", "Picking the passages that state something useful."
        ),
        Phase.CLAIMS.value: _e(
            "Recording statements", "Writing each fact down with the exact quote that backs it."
        ),
        Phase.VERIFY.value: _e(
            "Checking quotes",
            "Confirming each quote really appears in its source and supports the statement.",
        ),
        Phase.ANALYZE.value: _e(
            "Weighing the evidence",
            "Counting independent sources, spotting disagreements and rating each key point.",
        ),
        Phase.CHALLENGE.value: _e(
            "Challenging the answer", "Looking for evidence that would overturn the current answer."
        ),
        Phase.STOP_POLICY.value: _e(
            "Deciding whether to stop",
            "Checking whether the evidence is enough or another round is needed.",
        ),
        Phase.SYNTHESIZE.value: _e(
            "Writing the report", "Drafting the findings and checking every citation."
        ),
    },
    # Short label per activity-timeline event (EventType enum).
    "event": {
        EventType.RUN_STARTED.value: _e("Run started", "The research run was created."),
        EventType.PHASE_ENTERED.value: _e("New step", "The run moved to its next step."),
        EventType.PLAN_CREATED.value: _e(
            "Plan ready", "The key points and search queries were decided."
        ),
        EventType.TASK_STARTED.value: _e("Searching", "A search query started."),
        EventType.SOURCE_FOUND.value: _e("Source found", "A search returned a page worth reading."),
        EventType.SOURCE_FETCHED.value: _e("Source read", "A page was downloaded and stored."),
        EventType.SOURCE_FAILED.value: _e(
            "Source unavailable", "A page could not be read; the reason is shown."
        ),
        EventType.PASSAGES_CREATED.value: _e(
            "Text saved", "Passages of a page were stored for quoting."
        ),
        EventType.CLAIM_CREATED.value: _e(
            "Statement recorded", "A fact was written down with its quote."
        ),
        EventType.CLAIM_REJECTED.value: _e(
            "Statement rejected", "A statement was dropped because its quote was not in the source."
        ),
        EventType.CLAIM_VERIFIED.value: _e(
            "Statement checked", "A statement was checked against its quote."
        ),
        EventType.ORIGIN_UPDATED.value: _e(
            "Independence updated", "Sources were regrouped so copies count once."
        ),
        EventType.CONFLICT_DETECTED.value: _e(
            "Disagreement found", "Two sources give different answers."
        ),
        EventType.COVERAGE_UPDATED.value: _e("Support updated", "Each key point was re-rated."),
        EventType.ROUND_STARTED.value: _e(
            "New research round", "A follow-up round started to fill gaps."
        ),
        EventType.CHALLENGE_CREATED.value: _e(
            "Challenge planned", "An attempt to disprove the answer was set up."
        ),
        EventType.CHALLENGE_OUTCOME.value: _e(
            "Challenge result", "The attempt to disprove the answer finished."
        ),
        EventType.STOP_DECIDED.value: _e(
            "Stop decision made", "The controller decided whether the research is done."
        ),
        EventType.REPORT_DRAFT.value: _e("Report drafted", "The findings were written."),
        EventType.REPORT_VERIFIED.value: _e(
            "Report checked", "Every citation in the report was checked."
        ),
        EventType.BUDGET_WARNING.value: _e(
            "Budget warning", "A limit on searches, calls, cost or time is close."
        ),
        EventType.RUN_COMPLETED.value: _e("Run finished", "The run ended with a result."),
        EventType.RUN_FAILED.value: _e(
            "Run failed", "The run ended with an error; the reason is shown."
        ),
    },
}

# Enum each table must cover exactly (the completeness test and the TS generator use this).
TABLE_ENUMS: dict[str, type] = {
    "coverage_state": CoverageState,
    "final_state": FinalState,
    "verdict": Verdict,
    "challenge_outcome": ChallengeOutcome,
    "conflict_kind": ConflictKind,
    "conflict_status": ConflictStatus,
    "termination_reason": TerminationReason,
    "failure": FailureType,
    "source_status": SourceStatus,
    "certainty": CertaintyLabel,
    "phase": Phase,
    "event": EventType,
}


class TermEntry(BaseModel):
    singular: str  # lower-case plain name, e.g. "key point"
    plural: str
    meaning: str  # one sentence, shown as a tooltip


# Internal nouns a reader sees in the UI (slot, origin, round, claim) and their plain names. The UI
# reads these through `term()` in frontend/src/lib/terms.ts so the wording stays consistent.
TERMS: dict[str, TermEntry] = {
    "slot": TermEntry(
        singular="key point",
        plural="key points",
        meaning="One specific thing the research has to establish, such as a price or a rule.",
    ),
    "origin": TermEntry(
        singular="independent source",
        plural="independent sources",
        meaning="A source that does not simply copy another. Ten pages repeating one press release count as one.",
    ),
    "round": TermEntry(
        singular="research round",
        plural="research rounds",
        meaning="One pass of searching, reading and checking. Follow-up rounds fill gaps found in the previous one.",
    ),
    "claim": TermEntry(
        singular="statement",
        plural="statements",
        meaning="A fact or figure taken from a source, stored with the exact quote that backs it.",
    ),
}

# Shown at the top of every report and in the UI legend.
READING_GUIDE: list[str] = [
    "Every finding below is backed by a quote from a stored source. Each finding ends with "
    "citation numbers (like C12 in brackets); use one to see the exact quote and its source.",
    "Well supported means enough independent sources agree. Partly supported means the evidence "
    "is thin or disputed. Not enough evidence means nothing usable was found.",
    "Independent means the sources do not simply copy each other. Ten articles repeating one "
    "press release count as one source.",
    "The agent also tried to disprove its own conclusion. The section called "
    '"What could change the conclusion" lists what it tried.',
    '"Not enough to answer yet" is a valid result. It means the evidence was not there, and '
    "the report says what is missing.",
]


class GapText(BaseModel):
    reason: str  # full plain sentence: what is missing and why
    next_step: str  # what a reader can do about it


# Shared cases: Python and the generated TypeScript must both produce these (parity tests).
# Each row: the cell fields that go in, and the reason sentence that must come out.
GAP_CASES: list[dict] = [
    {
        "state": "RED",
        "origins": 0,
        "claims": 0,
        "conflicts": 0,
        "reason": "no usable evidence was found, so there is not enough evidence",
    },
    {
        "state": "AMBER",
        "origins": 2,
        "claims": 3,
        "conflicts": 1,
        "reason": "sources disagree and the difference is not yet explained, so it is partly supported",
    },
    {
        "state": "RED",
        "origins": 1,
        "claims": 1,
        "conflicts": 2,
        "reason": "sources disagree and the difference is not yet explained, so there is not enough evidence",
    },
    {
        "state": "AMBER",
        "origins": 1,
        "claims": 2,
        "conflicts": 0,
        "reason": "only one independent source, so it is partly supported",
    },
    {
        "state": "AMBER",
        "origins": 2,
        "claims": 2,
        "conflicts": 0,
        "reason": "the sources found only partly back this point, so it is partly supported",
    },
]


def gap_text(state: str, origins: int, claims: int, conflicts: int) -> GapText:
    """Plain-English reason and next step for one non-green coverage cell.

    Built only from stored cell fields (no parsing of the raw reason string), and the next step is
    borrowed from the matching glossary entry, so wording stays in one place.
    """
    cov = GLOSSARY["coverage_state"].get(state)
    if cov is None:
        raise KeyError(f"coverage_state.{state}")
    outcome = cov.label.lower()
    if claims == 0 and origins == 0 and conflicts == 0:
        why, step = "no usable evidence was found", cov.next_step
    elif conflicts > 0:
        why = "sources disagree and the difference is not yet explained"
        step = GLOSSARY["conflict_status"][ConflictStatus.OPEN.value].next_step
    elif origins <= 1:
        why = "only one independent source"
        step = GLOSSARY["certainty"][CertaintyLabel.SINGLE_ORIGIN.value].next_step
    else:
        why, step = "the sources found only partly back this point", cov.next_step
    return GapText(
        reason=f"{why}, so {'it is ' if state == 'AMBER' else 'there is '}{outcome}", next_step=step
    )


def entry(table: str, value: str) -> GlossaryEntry:
    """Lookup used by the backend; raises KeyError for an unknown value so a gap is never silent."""
    return GLOSSARY[table][value]


def label(table: str, value: str) -> str:
    return entry(table, value).label


def glossary_ts() -> str:
    """Render the glossary as a TypeScript module (generated; never hand-edited)."""
    import json

    lines = [
        "/* GENERATED by `make contracts` from contracts/glossary.py.",
        " * Source of truth: contracts/glossary.py. DO NOT EDIT BY HAND. */",
        "",
        "export interface GlossaryEntry {",
        "  label: string;",
        "  meaning: string;",
        "  next_step: string;",
        "}",
        "",
        "export const GLOSSARY = "
        + json.dumps(
            {t: {k: v.model_dump() for k, v in rows.items()} for t, rows in GLOSSARY.items()},
            indent=2,
            ensure_ascii=False,
        )
        + " as const satisfies Record<string, Record<string, GlossaryEntry>>;",
        "",
        "export type GlossaryTable = keyof typeof GLOSSARY;",
        "",
        "export interface TermEntry {",
        "  singular: string;",
        "  plural: string;",
        "  meaning: string;",
        "}",
        "",
        "export const TERMS = "
        + json.dumps({k: v.model_dump() for k, v in TERMS.items()}, indent=2, ensure_ascii=False)
        + " as const satisfies Record<string, TermEntry>;",
        "",
        "export type TermName = keyof typeof TERMS;",
        "",
        "/** Parity fixtures: lib/gap.ts must produce these reasons (tested). */",
        "export const GAP_CASES = "
        + json.dumps(GAP_CASES, indent=2, ensure_ascii=False)
        + " as const;",
        "",
        "export const READING_GUIDE: readonly string[] = "
        + json.dumps(READING_GUIDE, indent=2, ensure_ascii=False)
        + ";",
        "",
    ]
    return "\n".join(lines)
