"""Export the canonical Pydantic schemas to JSON Schema for TypeScript generation.

    uv run python -m contracts.schema_export           # write contracts/generated/schema.json
    uv run python -m contracts.schema_export --check   # fail if the committed file is stale

Pipeline: Pydantic models -> contracts/generated/schema.json -> (bun run gen:types) ->
contracts/generated/types.ts. Both generated files are committed and MUST NOT be edited by hand.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from pydantic import TypeAdapter

from contracts import events, models

GENERATED_DIR = Path(__file__).parent / "generated"
SCHEMA_PATH = GENERATED_DIR / "schema.json"

# Exported roots. Each becomes a named TypeScript type.
ROOTS: list[type] = [
    models.Run,
    models.Dimension,
    models.EvidenceSlot,
    models.Task,
    models.Source,
    models.Passage,
    models.Claim,
    models.EvidenceLink,
    models.Origin,
    models.Conflict,
    models.CoverageCell,
    models.Challenge,
    models.Report,
    models.StopDecision,
    models.Budget,
    models.Scope,
    models.RunCreate,
    models.BudgetUsage,
    models.Plan,
    models.DimensionRollup,
    models.RunSummary,
    models.RunState,
    models.ClaimEvidence,
    models.CitationRef,
    models.ReportView,
    events.Event,
    *events.EVENT_PAYLOADS.values(),
]


def build_schema() -> dict:
    """One JSON Schema document whose $defs hold every contract (deterministic key order)."""
    defs: dict = {}
    for root in ROOTS:
        schema = TypeAdapter(root).json_schema(ref_template="#/$defs/{model}")
        defs.update(schema.pop("$defs", {}))
        defs[root.__name__] = schema
    ordered = {k: defs[k] for k in sorted(defs)}
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "SarvamContracts",
        "description": "GENERATED by contracts/schema_export.py. Do not edit.",
        "type": "object",
        "properties": {name: {"$ref": f"#/$defs/{name}"} for name in ordered},
        "additionalProperties": False,
        "$defs": ordered,
    }


def render() -> str:
    return json.dumps(build_schema(), indent=2) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = SCHEMA_PATH.read_text(encoding="utf-8") if SCHEMA_PATH.exists() else ""
        if current != text:
            print(
                "contracts/generated/schema.json is stale; run `make contracts`.", file=sys.stderr
            )
            return 1
        print("contracts/generated/schema.json is up to date.")
        return 0
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {SCHEMA_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
